apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-mysql-pvc
  namespace: order
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi